### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(UntitledProject7)
add_subdirectory(UntitledProject7Content)
add_subdirectory(App)
add_subdirectory(Dependencies)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
    UntitledProject7plugin
    UntitledProject7Contentplugin)